export const deployments = [
  {
    name: "Alwaysdata",
    url: "https://nitro.alwaysdata.net/",
    dash: "https://admin.alwaysdata.com/",
    docs: "https://nitro.unjs.io/deploy/providers/alwaysdata",
  },
  {
    name: "AWS Lambda",
    url: "",
    dash: "https://aws.amazon.com/lambda/",
    docs: "https://nitro.unjs.io/deploy/providers/aws",
  },
  {
    name: "AWS Amplify",
    url: "",
    dash: "https://aws.amazon.com/amplify/",
    docs: "https://nitro.unjs.io/deploy/providers/aws-amplify",
  },
  {
    name: "Azure Static Web Apps",
    url: "https://delightful-mushroom-0f662f303.4.azurestaticapps.net/",
    dash: "https://azure.microsoft.com/en-us/products/app-service/static",
    docs: "https://nitro.unjs.io/deploy/providers/azure#azure-static-web-apps",
  },
  {
    name: "Azure Functions",
    url: "",
    dash: "https://azure.microsoft.com/en-us/products/functions",
    docs: "https://nitro.unjs.io/deploy/providers/azure#azure-functions",
  },
  {
    name: "Cleavr",
    url: "",
    dash: "https://app.cleavr.io/",
    docs: "https://nitro.unjs.io/deploy/providers/cleavr",
  },
  {
    name: "Cloudflare Pages",
    url: "https://nitro-deployment.pages.dev/",
    dash: "https://dash.cloudflare.com/",
    docs: "https://nitro.unjs.io/deploy/providers/cloudflare",
  },
  {
    name: "Deno Deploy",
    url: "https://nitro.deno.dev/",
    dash: "https://dash.deno.com/",
    docs: "https://nitro.unjs.io/deploy/providers/deno-deploy",
  },
  {
    name: "DigitalOcean",
    url: "",
    dash: "https://cloud.digitalocean.com/",
    docs: "https://nitro.unjs.io/deploy/providers/digitalocean",
  },
  {
    name: "Edgio",
    url: "",
    dash: "https://edgio.io/",
    docs: "https://nitro.unjs.io/deploy/providers/edgio",
  },
  {
    name: "Firebase Hosting",
    url: "",
    dash: "https://console.firebase.google.com/",
    docs: "https://nitro.unjs.io/deploy/providers/firebase",
  },
  {
    name: "Firebase App Hosting",
    url: "https://nitro-app--nitro-949b8.europe-west4.hosted.app/",
    dash: "https://console.firebase.google.com/",
    docs: "https://nitro.unjs.io/deploy/providers/firebase",
  },
  {
    name: "Flightcontrol",
    url: "",
    dash: "https://app.flightcontrol.dev/",
    docs: "https://nitro.unjs.io/deploy/providers/flightcontrol",
  },
  {
    name: "Genezio",
    broken: true,
    url: "https://0c2321a6-8af4-4d6b-bda9-46d197865f05.eu-central-1.cloud.genez.io/",
    dash: "https://app.genez.io/",
    docs: "https://nitro.unjs.io/deploy/providers/genezio",
  },
  {
    name: "Heroku",
    url: "",
    dash: "https://dashboard.heroku.com/",
    docs: "https://nitro.unjs.io/deploy/providers/heroku",
  },
  {
    name: "Koyeb",
    url: "https://shy-constancy-pi0-229c4ed6.koyeb.app/",
    dash: "https://app.koyeb.com/",
    docs: "https://nitro.unjs.io/deploy/providers/koyeb",
  },
  {
    name: "Netlify Functions",
    url: "https://nitro-deployment.netlify.app/",
    dash: "https://app.netlify.com/",
    docs: "https://nitro.unjs.io/deploy/providers/netlify",
  },
  {
    name: "Netflify Edge",
    url: "https://nitro-deployment-edge.netlify.app/",
    dash: "https://app.netlify.com/",
    docs: "https://nitro.unjs.io/deploy/providers/netlify#netlify-edge-functions",
  },
  {
    name: "Platform.sh",
    url: "https://main-bvxea6i-gtpvl3hzdfys2.de-2.platformsh.site/",
    dash: "https://console.platform.sh/",
    docs: "https://nitro.build/deploy/providers/platform-sh",
  },
  {
    name: "Render.com",
    broken: true,
    url: "https://nitro-app.onrender.com/",
    dash: "https://dashboard.render.com/",
    docs: "https://nitro.unjs.io/deploy/providers/render",
  },
  {
    name: "Stormkit",
    url: "https://nitro.stormkit.dev/",
    dash: "https://app.stormkit.io/",
    docs: "https://nitro.unjs.io/deploy/providers/stormkit",
  },
  {
    name: "Vercel",
    url: "https://nitro-app.vercel.app/",
    dash: "https://vercel.com/",
    docs: "https://nitro.unjs.io/deploy/providers/vercel",
  },
  {
    name: "Vercel Edge",
    url: "https://nitro-app-edge.vercel.app/",
    dash: "https://vercel.com/",
    docs: "https://nitro.unjs.io/deploy/providers/vercel#vercel-edge-functions",
  },
  {
    name: "Zeabur",
    url: "",
    dash: "https://dash.zeabur.com/",
    docs: "https://nitro.unjs.io/deploy/providers/zeabur",
  },
  {
    name: "Zerops",
    url: "https://app-a46-3000.prg1.zerops.app/",
    dash: "https://app.zerops.io/",
    docs: "https://nitro.unjs.io/deploy/providers/zerops",
  },
];
