export default defineEventHandler(() => {
  const links = [
    '/api/hello'
  ]
  return `<!DOCTYPE html>
  <html lang="en">
    <head>
      <meta charset="utf-8">
      <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🐣</text></svg>" />
      <title>Nitro Test Deployment</title>
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@picocss/pico/css/pico.min.css">
    </head>
    <body>
      <main class="container">
        <article>
          <header>
            <h1 align="center">🐣 Nitro Test Deployment </h1>
          </header>
          <div>
            <ul>
        ${links.map(link => `        <li><a href="${link}">${link}</a></li>`).join('\n')}
            </ul>
          </div>
          <footer>
            Generated by <a href="https://nitro.unjs.io/" target="_blank" rel="noopener">Nitro</a> at ${new Date().toUTCString()}
            |
            <a href="https://github.com/unjs/nitro-deploys" target="_blank" rel="noopener">Github</a>
          </footer>
        </article>
      </main>
    </body>
</html>`
})
