name: Deno Deploy
on:
  push:
    branches:
      - main
      - deno-deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm build
        env:
          NITRO_PRESET: deno_deploy
      - uses: denoland/deployctl@v1
        with:
          project: "nitro"
          entrypoint: "server/index.ts"
          root: ".output"
